[tool.poetry]
name = "aiogram"
version = "3.0.0-alpha.0"
description = "is a pretty simple and fully asynchronous framework for Telegram Bot API"
authors = ["Alex Root Junior <jroot.junior@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://aiogram.readthedocs.io/"
documentation = "https://aiogram.readthedocs.io/"


[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
pydantic = "^1.1"
Babel = "^2.7"
pytest-cov = "^2.8"
aiofiles = "^0.4.0"
pytest-mock = "^1.11"
pymdown-extensions = "^6.1"
mkautodoc = "^0.1.0"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
isort = "^4.3"
flake8 = "^3.7"
mypy = "^0.740.0"
pytest = "^5.2"
pytest-asyncio = "^0.10.0"
aresponses = "^1.1"
uvloop = "^0.14.0"
mkdocs = "^1.0"
mkdocs-material = "^4.4"
pygments = "^2.4"
pymdown-extensions = "^6.1"
pytest-mypy = "^0.4.2"
asynctest = "^0.13.0"

[tool.black]
line-length = 99
target-version = ['py37', 'py38']
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | build
  | dist
  | venv
  | docs
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
