name: PyPy Tests

on:
  push:
    branches:
      - dev-3.x
    paths:
      - ".github/workflows/pypy-tests.yml"
      - "aiogram/**"
      - "tests/**"
      - "codecov.yaml"
      - "pyproject.toml"
  pull_request:
    branches:
      - dev-3.x
    paths:
      - ".github/workflows/pypy-tests.yml"
      - "aiogram/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        python-version:
          - 'pypy3.8'
          - 'pypy3.9'

    defaults:
      # Windows sucks. Force use bash instead of PowerShell
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install project dependencies
        run: |
          pip install -e .[dev,test,redis,proxy,i18n,fast]

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 6

      - name: Run tests
        run: |
          flags=""
          pytest $flags
