name: Tests

on:
  push:
    branches:
      - dev-3.x
  pull_request:
    branches:
      - dev-3.x

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry==1.0
          poetry install

      - name: Lint code
        run: |
          poetry run flake8 aiogram test
          poetry run mypy aiogram tests

      - name: Run tests
        run: |
          poetry run pytest
